local M = {}

local ROOT_MARKERS = {
	".clangd",
	".clang-tidy",
	".clang-format",
	"compile_commands.json",
	"compile_flags.txt",
	"configure.ac",
	"CMakeLists.txt",
	"Makefile",
	".git",
}

local CMAKE_BUILD_DIRS = {
	"build",
	"build-debug",
	"build-release",
	"cmake-build-debug",
	"cmake-build-release",
}

-- Per-language fallback compile flags used when a project has neither
-- compile_commands.json nor a hand-written .clangd / compile_flags.txt.
local CLANGD_FALLBACK_TEMPLATE = [[
# Generated by :CppCompileCommands - edit this file freely.
If:
  PathMatch: .*\.(c|h)$
CompileFlags:
  Add: [-std=c17, -Wall, -Wextra, -Wpedantic]
---
If:
  PathMatch: .*\.(cc|cpp|cxx|hpp|hxx|tpp)$
CompileFlags:
  Add: [-std=c++17, -Wall, -Wextra, -Wpedantic]
]]

local function mason_bin()
	return vim.fn.stdpath("data") .. "/mason/bin"
end

local function notify(msg, level)
	vim.notify(msg, level or vim.log.levels.INFO)
end

local function project_root()
	local fname = vim.api.nvim_buf_get_name(0)
	if fname == "" then
		fname = vim.fn.getcwd()
	end
	return vim.fs.root(fname, ROOT_MARKERS) or vim.fn.getcwd()
end

local function link_compile_commands(source, root)
	local dest = root .. "/compile_commands.json"
	if vim.fn.filereadable(dest) == 1 then
		vim.fn.delete(dest)
	end
	if vim.fn.symlink(source, dest) ~= 1 then
		pcall(vim.fn.writefile, vim.fn.readfile(source), dest)
	end
	return dest
end

local function existing_cmake_database(root)
	for _, dir in ipairs(CMAKE_BUILD_DIRS) do
		local cc = root .. "/" .. dir .. "/compile_commands.json"
		if vim.fn.filereadable(cc) == 1 then
			return cc
		end
	end
	return nil
end

local function setup_cmake(root)
	local existing = existing_cmake_database(root)
	if existing then
		return existing
	end

	local build_dir = root .. "/build"
	vim.fn.mkdir(build_dir, "p")
	local out = vim.fn.system(
		"cmake -S " .. vim.fn.shellescape(root) .. " -B " .. vim.fn.shellescape(build_dir)
			.. " -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 2>&1"
	)
	if vim.v.shell_error ~= 0 then
		notify("CMake configure failed:\n" .. out, vim.log.levels.ERROR)
		return nil
	end

	local cc = build_dir .. "/compile_commands.json"
	if vim.fn.filereadable(cc) == 1 then
		return cc
	end
	notify("CMake finished but produced no compile_commands.json:\n" .. out, vim.log.levels.WARN)
	return nil
end

local function setup_bear(root)
	local bear = mason_bin() .. "/bear"
	if vim.fn.executable(bear) ~= 1 then
		bear = "bear"
	end
	if vim.fn.executable(bear) ~= 1 then
		return nil
	end

	local build_cmd = vim.fn.input("Build command to wrap with bear: ", "make -j", "shellcmd")
	if build_cmd == "" then
		return nil
	end

	local out = vim.fn.system(
		"cd " .. vim.fn.shellescape(root) .. " && " .. vim.fn.shellescape(bear) .. " -- " .. build_cmd .. " 2>&1"
	)
	local cc = root .. "/compile_commands.json"
	if vim.v.shell_error == 0 and vim.fn.filereadable(cc) == 1 then
		return cc
	end
	notify("bear failed to produce compile_commands.json:\n" .. out, vim.log.levels.ERROR)
	return nil
end

local function setup_clangd_fallback(root)
	local clangd_file = root .. "/.clangd"
	if vim.fn.filereadable(clangd_file) ~= 1 then
		vim.fn.writefile(vim.split(CLANGD_FALLBACK_TEMPLATE, "\n", { trimempty = true }), clangd_file)
	end
	return clangd_file
end

local function cpp_compile_commands()
	local root = project_root()

	if vim.fn.filereadable(root .. "/compile_commands.json") == 1 then
		notify("compile_commands.json already exists in " .. root)
		return
	end

	if vim.fn.filereadable(root .. "/compile_flags.txt") == 1 or vim.fn.filereadable(root .. "/.clangd") == 1 then
		notify("compile_flags.txt or .clangd already exists in " .. root .. " - clangd will use it.")
		return
	end

	local database
	if vim.fn.filereadable(root .. "/CMakeLists.txt") == 1 then
		database = setup_cmake(root)
	else
		database = setup_bear(root)
	end

	if database then
		local link = link_compile_commands(database, root)
		notify("compile database ready: " .. link)
		vim.schedule(function()
			pcall(vim.cmd, "LspRestart clangd")
		end)
	else
		local flags = setup_clangd_fallback(root)
		notify(
			"No compile_commands.json available. Wrote fallback flags to " .. flags
				.. " - restart clangd (:LspRestart clangd).",
			vim.log.levels.WARN
		)
	end
end

local function show_output(title, content)
	local lines = vim.split(content, "\n", { trimempty = true })
	if #lines == 0 then
		lines = { "(no output)" }
	end
	vim.cmd("split " .. title)
	vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
	vim.cmd("setlocal buftype=nofile nobuflisted bufhidden=wipe")
	vim.cmd("setlocal nomodifiable")
end

local function cpp_run()
	local fname = vim.api.nvim_buf_get_name(0)
	if fname == "" then
		return notify("No file to run.", vim.log.levels.ERROR)
	end
	vim.cmd("w")

	local compiler = vim.bo.filetype == "c" and "gcc" or "g++"
	if vim.fn.executable(compiler) ~= 1 then
		return notify("Compiler not found: " .. compiler, vim.log.levels.ERROR)
	end

	local out_bin = "/tmp/" .. vim.fn.fnamemodify(fname, ":t") .. ".out"
	local build_out = vim.fn.system(
		compiler .. " -Wall -Wextra " .. vim.fn.shellescape(fname) .. " -o " .. vim.fn.shellescape(out_bin) .. " 2>&1"
	)
	if vim.v.shell_error ~= 0 then
		return show_output("__Cpp_Output__", "Build failed:\n" .. build_out)
	end

	local run_out = vim.fn.system(vim.fn.shellescape(out_bin) .. " 2>&1")
	local exit_code = vim.v.shell_error
	show_output("__Cpp_Output__", run_out .. "\n\n(exit code: " .. exit_code .. ")")
end

-- Net ( open / [ open minus close for a line, ignoring string literals.
local function bracket_delta(line)
	local stripped = line:gsub('"[^"]*"', "")
	local _, open_count = stripped:gsub("[%(%[]", "")
	local _, close_count = stripped:gsub("[%)%]]", "")
	return open_count - close_count
end

-- True when a `(`/`[` opened on a line before `row` is still unclosed.
local function continuation_before(row)
	local balance = 0
	for _, line in ipairs(vim.api.nvim_buf_get_lines(0, 0, row - 1, false)) do
		balance = balance + bracket_delta(line)
	end
	return balance > 0
end

local function line_needs_semicolon(code)
	if code == "" then
		return false
	end
	if code:match("^%s*#") then
		return false
	end
	if code:match("^%s*//") or code:match("^%s*/%*") then
		return false
	end
	if code:match("[{}%;:,]$") then
		return false
	end
	if code:match("[=+*/%&|<>%-]$") then
		return false
	end
	if code:match('^%s*"') then
		return false
	end
	if bracket_delta(code) > 0 then
		return false
	end
	if code:match("^%s*(if|for|while|switch|catch|else%s*if)%s*%(.+%)%s*$") then
		return false
	end
	if code:match("^%s*(else|do|try)%s*$") then
		return false
	end
	if code:match("^%s*case%s+.+:%s*$") or code:match("^%s*default:%s*$") then
		return false
	end
	if code:match("^%s*namespace%s+") then
		return false
	end
	return true
end

-- Returns the line with a missing trailing semicolon added, or nil if untouched.
local function semicolon_fixed(line)
	local trimmed = line:gsub("%s+$", "")
	if trimmed == "" then
		return nil
	end

	local comment
	local code = trimmed
	local pos = trimmed:find("//", 1, true)
	if pos and not trimmed:match("^%s*//") then
		comment = trimmed:sub(pos)
		code = trimmed:sub(1, pos - 1):gsub("%s+$", "")
		if code == "" then
			return nil
		end
	end

	if not line_needs_semicolon(code) then
		return nil
	end

	return comment and (code .. "; " .. comment) or (code .. ";")
end

local function fix_missing_semicolons()
	local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
	local changed = false
	local balance = 0
	for i, line in ipairs(lines) do
		if balance <= 0 then
			local fixed = semicolon_fixed(line)
			if fixed and fixed ~= line then
				lines[i] = fixed
				changed = true
			end
		end
		balance = balance + bracket_delta(line)
	end
	if changed then
		vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
	end
end

local function press_enter()
	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<CR>", true, false, true), "n", false)
end

-- Normal-mode `o` / `O`: append a missing `;` to the current statement, then open the line.
local function open_line(key)
	local row = vim.api.nvim_win_get_cursor(0)[1]
	if not continuation_before(row) then
		local fixed = semicolon_fixed(vim.api.nvim_get_current_line())
		if fixed then
			vim.api.nvim_buf_set_text(0, row - 1, 0, row - 1, -1, { fixed })
		end
	end
	local prefix = vim.v.count > 0 and tostring(vim.v.count) or ""
	vim.api.nvim_feedkeys(prefix .. key, "n", false)
end

-- Insert-mode <CR>: append a missing `;` to the current statement, then newline.
local function semicolon_on_enter()
	local row, col = unpack(vim.api.nvim_win_get_cursor(0))
	local line = vim.api.nvim_get_current_line()

	if line:sub(1, col + 1) ~= line:gsub("%s+$", "") then
		press_enter()
		return
	end

	if continuation_before(row) then
		press_enter()
		return
	end

	local fixed = semicolon_fixed(line)
	if fixed and fixed ~= line then
		vim.api.nvim_buf_set_text(0, row - 1, 0, row - 1, -1, { fixed })
		vim.api.nvim_win_set_cursor(0, { row, #fixed })
	end
	press_enter()
end

function M.setup()
	vim.api.nvim_create_user_command("CppCompileCommands", cpp_compile_commands, {
		desc = "Generate compile_commands.json (or fallback .clangd) for clangd",
	})

	vim.api.nvim_create_user_command("CppRun", cpp_run, {
		desc = "Build and run the current C/C++ file",
	})

	vim.api.nvim_create_autocmd("FileType", {
		pattern = { "c", "cpp" },
		callback = function()
			vim.keymap.set("n", "<leader>r", cpp_run, { buffer = true, desc = "Build and run this file" })
			vim.keymap.set("n", "o", function()
				open_line("o")
			end, { buffer = true, desc = "Add ; if needed, then open below" })
			vim.keymap.set("n", "O", function()
				open_line("O")
			end, { buffer = true, desc = "Add ; if needed, then open above" })
			vim.keymap.set("i", "<CR>", semicolon_on_enter, {
				buffer = true,
				desc = "Append missing ; then insert newline",
			})
		end,
	})

	vim.api.nvim_create_autocmd("BufWritePre", {
		pattern = { "*.c", "*.h", "*.cc", "*.cpp", "*.cxx", "*.hpp", "*.hxx", "*.tpp" },
		callback = fix_missing_semicolons,
		desc = "Append missing semicolons to C/C++ statement lines",
	})
end

return M
